<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Frank.UblSharp.Internals.XsdCodeGenerator\Frank.UblSharp.Internals.XsdCodeGenerator.csproj"
                          ReferenceOutputAssembly="false"
                          OutputItemType="Analyzer"
                          PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="xsd\**\*" CopyToOutputDirectory="PreserveNewest" />
        <EmbeddedResource Include="xsd\**\*" />
    </ItemGroup>

</Project>
